import tkinter
from tkinter import *
root=Tk()
root.title("Book Directory")
def show():
 print("hello guys")
root.resizable(True,True)
root.minsize(650,200)
root.maxsize(500,500)
la1=Label(root,text="Title" ,width=10,font=90)
la1.grid(row=0,column=0)
e1=Entry(root,width=30)
e1.grid(row=0,column=1)
la2=Label(root,text="Author",width=10,font=90)
la2.grid(row=0,column=2)
e2=Entry(root,width=30)
e2.grid(row=0,column=3)
la3=Label(root,text="Year",width=10,font=90)
la3.grid(row=1,column=0)
e3=Entry(root,width=30)
e3.grid(row=1,column=1)
la4=Label(root,text="ISBN No",width=10,font=90)
la4.grid(row=1,column=2)
e4=Entry(root,width=30)
e4.grid(row=1,column=3)
l=Listbox(root,height=6,width=60)
l.grid(row=2,column=0,rowspan=6,columnspan=2)
s=Scrollbar(root)
s.grid(row=2,column=2,rowspan=6)
l.configure(yscrollcommand=s.set)
s.configure(command=l.yview)
b1=Button(root,text="View All",command=show,width=15)
b1.grid(row=2,column=3)
b2=Button(root,text="Sreach Entry",command=show,width=15)
b2.grid(row=3,column=3)
b3=Button(root,text="Add Entry",command=show,width=15)
b3.grid(row=4,column=3)
b4=Button(root,text="Update Selected",command=show,width=15)
b4.grid(row=5,column=3)
b5=Button(root,text="Add Entry",command=show,width=15)
b5.grid(row=6,column=3)
b6=Button(root,text="Update Selected",command=show,width=15)
b6.grid(row=7,column=3)
root.mainloop()

